$(document).ready(function(){
    $(".profile1").click(function(){
    	$("#Al").toggle();
      $(".profile1").toggle();
    });
    $("#Al").click(function(){
      $(".profile1").toggle();
      $("#Al").toggle();
    });

    $(".profile2").click(function(){
    	$("#Ben").toggle();
      $(".profile2").toggle();
    });
    $("#Ben").click(function(){
      $(".profile2").toggle();
      $("#Ben").toggle();
    });

    $(".profile3").click(function(){
      $("#Flo").toggle();
      $(".profile3").toggle();
    });
    $("#Flo").click(function(){
      $(".profile3").toggle();
      $("#Flo").toggle();
    });

    $(".profile4").click(function(){
    	$("#Jez").toggle();
      $(".profile4").toggle();
    });
    $("#Jez").click(function(){
      $(".profile4").toggle();
      $("#Jez").toggle();
    });

    $(".profile5").click(function(){
      $("#Josh").toggle();
      $(".profile5").toggle();
    });
    $("#Josh").click(function(){
      $(".profile5").toggle();
      $("#Josh").toggle();
    });

    $(".profile6").click(function(){
    	$("#Kyla").toggle();
      $(".profile6").toggle();
    });
    $("#Kyla").click(function(){
      $(".profile6").toggle();
      $("#Kyla").toggle();
    });

    $(".profile7").click(function(){
    	$("#Lolo").toggle();
      $(".profile7").toggle();
    });
    $("#Lolo").click(function(){
      $(".profile7").toggle();
      $("#Lolo").toggle();
    });

    $(".profile8").click(function(){
    	$("#MJ").toggle();
      $(".profile8").toggle();
    });
    $("#MJ").click(function(){
      $(".profile8").toggle();
      $("#MJ").toggle();
    });

    $(".profile9").click(function(){
    	$("#Myles").toggle();
      $(".profile9").toggle();
    });
    $("#Myles").click(function(){
      $(".profile9").toggle();
      $("#Myles").toggle();
    });

    $(".profile10").click(function(){
    	$("#Rizza").toggle();
      $(".profile10").toggle();
    });
    $("#Rizza").click(function(){
      $(".profile10").toggle();
      $("#Rizza").toggle();
    });

    $(".post").click(function(){
      $(".docs").toggle();
      $(".docs2").hide();
      $(".docs3").hide();
      $(".docs4").hide();
      $(".docs5").hide();
      $(".docs6").hide();
      $(".docs7").hide();
      $(".docs8").hide();
      $(".docs9").hide();
      $(".docs10").hide();
      $(".docs11").hide();
      $(".docs12").hide();
      $(".docs13").hide();
      $(".docs14").hide();
      $(".docs15").hide();
      $(".docs16").hide();
      $(".docs17").hide();
      $(".docs18").hide();
      $(".docs19").hide();
      $(".docs20").hide();
    });

    $(".post2").click(function(){
      $(".docs2").toggle();
      $(".docs").hide();
      $(".docs3").hide();
      $(".docs4").hide();
      $(".docs5").hide();
      $(".docs6").hide();
      $(".docs7").hide();
      $(".docs8").hide();
      $(".docs9").hide();
      $(".docs10").hide();
      $(".docs11").hide();
      $(".docs12").hide();
      $(".docs13").hide();
      $(".docs14").hide();
      $(".docs15").hide();
      $(".docs16").hide();
      $(".docs17").hide();
      $(".docs18").hide();
      $(".docs19").hide();
      $(".docs20").hide();
    });

    $(".post3").click(function(){
      $(".docs3").toggle();
      $(".docs2").hide();
      $(".docs").hide();
      $(".docs4").hide();
      $(".docs5").hide();
      $(".docs6").hide();
      $(".docs7").hide();
      $(".docs8").hide();
      $(".docs9").hide();
      $(".docs10").hide();
      $(".docs11").hide();
      $(".docs12").hide();
      $(".docs13").hide();
      $(".docs14").hide();
      $(".docs15").hide();
      $(".docs16").hide();
      $(".docs17").hide();
      $(".docs18").hide();
      $(".docs19").hide();
      $(".docs20").hide();
    });

    $(".post4").click(function(){
      $(".docs4").toggle();
      $(".docs2").hide();
      $(".docs3").hide();
      $(".docs").hide();
      $(".docs5").hide();
      $(".docs6").hide();
      $(".docs7").hide();
      $(".docs8").hide();
      $(".docs9").hide();
      $(".docs10").hide();
      $(".docs11").hide();
      $(".docs12").hide();
      $(".docs13").hide();
      $(".docs14").hide();
      $(".docs15").hide();
      $(".docs16").hide();
      $(".docs17").hide();
      $(".docs18").hide();
      $(".docs19").hide();
      $(".docs20").hide();
    });

    $(".post5").click(function(){
      $(".docs5").toggle();
      $(".docs2").hide();
      $(".docs3").hide();
      $(".docs4").hide();
      $(".docs").hide();
      $(".docs6").hide();
      $(".docs7").hide();
      $(".docs8").hide();
      $(".docs9").hide();
      $(".docs10").hide();
      $(".docs11").hide();
      $(".docs12").hide();
      $(".docs13").hide();
      $(".docs14").hide();
      $(".docs15").hide();
      $(".docs16").hide();
      $(".docs17").hide();
      $(".docs18").hide();
      $(".docs19").hide();
      $(".docs20").hide();
    });

    $(".post6").click(function(){
      $(".docs6").toggle();
      $(".docs2").hide();
      $(".docs3").hide();
      $(".docs4").hide();
      $(".docs5").hide();
      $(".docs").hide();
      $(".docs7").hide();
      $(".docs8").hide();
      $(".docs9").hide();
      $(".docs10").hide();
      $(".docs11").hide();
      $(".docs12").hide();
      $(".docs13").hide();
      $(".docs14").hide();
      $(".docs15").hide();
      $(".docs16").hide();
      $(".docs17").hide();
      $(".docs18").hide();
      $(".docs19").hide();
      $(".docs20").hide();
    });

    $(".post7").click(function(){
      $(".docs7").toggle();
      $(".docs2").hide();
      $(".docs3").hide();
      $(".docs4").hide();
      $(".docs5").hide();
      $(".docs6").hide();
      $(".docs").hide();
      $(".docs8").hide();
      $(".docs9").hide();
      $(".docs10").hide();
      $(".docs11").hide();
      $(".docs12").hide();
      $(".docs13").hide();
      $(".docs14").hide();
      $(".docs15").hide();
      $(".docs16").hide();
      $(".docs17").hide();
      $(".docs18").hide();
      $(".docs19").hide();
      $(".docs20").hide();
    });
    $(".post8").click(function(){
      $(".docs8").toggle();
      $(".docs2").hide();
      $(".docs3").hide();
      $(".docs4").hide();
      $(".docs5").hide();
      $(".docs6").hide();
      $(".docs7").hide();
      $(".docs").hide();
      $(".docs9").hide();
      $(".docs10").hide();
      $(".docs11").hide();
      $(".docs12").hide();
      $(".docs13").hide();
      $(".docs14").hide();
      $(".docs15").hide();
      $(".docs16").hide();
      $(".docs17").hide();
      $(".docs18").hide();
      $(".docs19").hide();
      $(".docs20").hide();
    });
    $(".post9").click(function(){
      $(".docs9").toggle();
      $(".docs2").hide();
      $(".docs3").hide();
      $(".docs4").hide();
      $(".docs5").hide();
      $(".docs6").hide();
      $(".docs7").hide();
      $(".docs8").hide();
      $(".docs").hide();
      $(".docs10").hide();
      $(".docs11").hide();
      $(".docs12").hide();
      $(".docs13").hide();
      $(".docs14").hide();
      $(".docs15").hide();
      $(".docs16").hide();
      $(".docs17").hide();
      $(".docs18").hide();
      $(".docs19").hide();
      $(".docs20").hide();
    });
    $(".post10").click(function(){
      $(".docs10").toggle();
      $(".docs2").hide();
      $(".docs3").hide();
      $(".docs4").hide();
      $(".docs5").hide();
      $(".docs6").hide();
      $(".docs7").hide();
      $(".docs8").hide();
      $(".docs9").hide();
      $(".docs").hide();
      $(".docs11").hide();
      $(".docs12").hide();
      $(".docs13").hide();
      $(".docs14").hide();
      $(".docs15").hide();
      $(".docs16").hide();
      $(".docs17").hide();
      $(".docs18").hide();
      $(".docs19").hide();
      $(".docs20").hide();
    });
    $(".post11").click(function(){
      $(".docs11").toggle();
      $(".docs2").hide();
      $(".docs3").hide();
      $(".docs4").hide();
      $(".docs5").hide();
      $(".docs6").hide();
      $(".docs7").hide();
      $(".docs8").hide();
      $(".docs9").hide();
      $(".docs10").hide();
      $(".docs").hide();
      $(".docs12").hide();
      $(".docs13").hide();
      $(".docs14").hide();
      $(".docs15").hide();
      $(".docs16").hide();
      $(".docs17").hide();
      $(".docs18").hide();
      $(".docs19").hide();
      $(".docs20").hide();
    });
    $(".post12").click(function(){
      $(".docs12").toggle();
      $(".docs2").hide();
      $(".docs3").hide();
      $(".docs4").hide();
      $(".docs5").hide();
      $(".docs6").hide();
      $(".docs7").hide();
      $(".docs8").hide();
      $(".docs9").hide();
      $(".docs10").hide();
      $(".docs11").hide();
      $(".docs").hide();
      $(".docs13").hide();
      $(".docs14").hide();
      $(".docs15").hide();
      $(".docs16").hide();
      $(".docs17").hide();
      $(".docs18").hide();
      $(".docs19").hide();
      $(".docs20").hide();
    });
    $(".post13").click(function(){
      $(".docs13").toggle();
      $(".docs2").hide();
      $(".docs3").hide();
      $(".docs4").hide();
      $(".docs5").hide();
      $(".docs6").hide();
      $(".docs7").hide();
      $(".docs8").hide();
      $(".docs9").hide();
      $(".docs10").hide();
      $(".docs11").hide();
      $(".docs12").hide();
      $(".docs").hide();
      $(".docs14").hide();
      $(".docs15").hide();
      $(".docs16").hide();
      $(".docs17").hide();
      $(".docs18").hide();
      $(".docs19").hide();
      $(".docs20").hide();
    });
    $(".post14").click(function(){
      $(".docs14").toggle();
      $(".docs2").hide();
      $(".docs3").hide();
      $(".docs4").hide();
      $(".docs5").hide();
      $(".docs6").hide();
      $(".docs7").hide();
      $(".docs8").hide();
      $(".docs9").hide();
      $(".docs10").hide();
      $(".docs11").hide();
      $(".docs12").hide();
      $(".docs13").hide();
      $(".docs").hide();
      $(".docs15").hide();
      $(".docs16").hide();
      $(".docs17").hide();
      $(".docs18").hide();
      $(".docs19").hide();
      $(".docs20").hide();
    });
    $(".post15").click(function(){
      $(".docs15").toggle();
      $(".docs2").hide();
      $(".docs3").hide();
      $(".docs4").hide();
      $(".docs5").hide();
      $(".docs6").hide();
      $(".docs7").hide();
      $(".docs8").hide();
      $(".docs9").hide();
      $(".docs10").hide();
      $(".docs11").hide();
      $(".docs12").hide();
      $(".docs13").hide();
      $(".docs14").hide();
      $(".docs").hide();
      $(".docs16").hide();
      $(".docs17").hide();
      $(".docs18").hide();
      $(".docs19").hide();
      $(".docs20").hide();
    });
    $(".post16").click(function(){
      $(".docs16").toggle();
      $(".docs2").hide();
      $(".docs3").hide();
      $(".docs4").hide();
      $(".docs5").hide();
      $(".docs6").hide();
      $(".docs7").hide();
      $(".docs8").hide();
      $(".docs9").hide();
      $(".docs10").hide();
      $(".docs11").hide();
      $(".docs12").hide();
      $(".docs13").hide();
      $(".docs14").hide();
      $(".docs15").hide();
      $(".docs").hide();
      $(".docs17").hide();
      $(".docs18").hide();
      $(".docs19").hide();
      $(".docs20").hide();
    });
    $(".post17").click(function(){
      $(".docs17").toggle();
      $(".docs2").hide();
      $(".docs3").hide();
      $(".docs4").hide();
      $(".docs5").hide();
      $(".docs6").hide();
      $(".docs7").hide();
      $(".docs8").hide();
      $(".docs9").hide();
      $(".docs10").hide();
      $(".docs11").hide();
      $(".docs12").hide();
      $(".docs13").hide();
      $(".docs14").hide();
      $(".docs15").hide();
      $(".docs16").hide();
      $(".docs").hide();
      $(".docs18").hide();
      $(".docs19").hide();
      $(".docs20").hide();
    });
    $(".post18").click(function(){
      $(".docs18").toggle();
      $(".docs2").hide();
      $(".docs3").hide();
      $(".docs4").hide();
      $(".docs5").hide();
      $(".docs6").hide();
      $(".docs7").hide();
      $(".docs8").hide();
      $(".docs9").hide();
      $(".docs10").hide();
      $(".docs11").hide();
      $(".docs12").hide();
      $(".docs13").hide();
      $(".docs14").hide();
      $(".docs15").hide();
      $(".docs16").hide();
      $(".docs17").hide();
      $(".docs").hide();
      $(".docs19").hide();
      $(".docs20").hide();
    });
    $(".post19").click(function(){
      $(".docs19").toggle();
      $(".docs2").hide();
      $(".docs3").hide();
      $(".docs4").hide();
      $(".docs5").hide();
      $(".docs6").hide();
      $(".docs7").hide();
      $(".docs8").hide();
      $(".docs9").hide();
      $(".docs10").hide();
      $(".docs11").hide();
      $(".docs12").hide();
      $(".docs13").hide();
      $(".docs14").hide();
      $(".docs15").hide();
      $(".docs16").hide();
      $(".docs17").hide();
      $(".docs18").hide();
      $(".docs").hide();
      $(".docs20").hide();
    });
    $(".post20").click(function(){
      $(".docs20").toggle();
      $(".docs2").hide();
      $(".docs3").hide();
      $(".docs4").hide();
      $(".docs5").hide();
      $(".docs6").hide();
      $(".docs7").hide();
      $(".docs8").hide();
      $(".docs9").hide();
      $(".docs10").hide();
      $(".docs11").hide();
      $(".docs12").hide();
      $(".docs13").hide();
      $(".docs14").hide();
      $(".docs15").hide();
      $(".docs16").hide();
      $(".docs17").hide();
      $(".docs18").hide();
      $(".docs19").hide();
      $(".docs").hide();
    });
});
